[package]
name = "jaksel-lang"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.15.1"
thiserror = "2.0.17"

[dev-dependencies]
glob_test = "0.1.0"
insta = { version = "1.44.0", features = ["yaml"] }
